<?php
// $Id: editview.module,v 1.7 2009/02/17 00:39:01 agileware Exp $

/**
 * @file
 * Plug-in to make an editable node view.
 */

/**
 * @addtogroup editview
 * @{
 */

/**
 * Implementation of hook_views_api().
 */
function editview_views_api() {
  return array(
    'api' => 2.0,
    'path' => drupal_get_path('module', 'editview') .'/includes',
  );
}

/**
 * Implementation of hook_help().
 */
function editview_help($path, $arg) {
  switch ($path) {
    case 'admin/help#editview':
      return '<p>'. t('Editview is a Views plug-in that allows you to create views in which nodes are editable and new nodes can be created. Editview works with or without JavaScript enabled.') .'</pre>'."\n".
      '<h3>'. t('Usage') .'</h3>'."\n".
      '<p>'. t('Editable node views are created just like any other type of view, with a few caveats:') .'</p>'."\n".
      '<ol>'."\n".
      '  <li>'. t('Add or edit a node view.') .'</li>'."\n".
      '  <li>'. t('If you want to be able to add new nodes in the view, set the style to Editview in Basic settings. Otherwise, you can choose any style that allows you to set a row style and set the row style to Editview.') .'</li>'."\n".
      '  <li>'. t('Include any required fields in the view, or new nodes will fail validation.') .'</li>'."\n".
      '</ol>'."\n";
  }
}

/**
 * Implementation of hook_menu().
 */
function editview_menu() {
  $items['editview_js'] = array(
    'page callback' => 'editview_js',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'file' => 'includes/editview.views.inc',
  );
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function editview_theme() {
  return array(
    'editview_node_form' => array(
      'arguments' => array('form' => NULL),
      'file' => 'editview.theme.inc',
      'path' => drupal_get_path('module', 'editview') .'/theme',
    ),
  );
}

/**
 * @} End of "addtogroup editview".
 */
